/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 model.gltf 
Author: akhalas (https://sketchfab.com/akhalas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cafe-racer-bike-cg-model-6fecde3fa3d04764a19dd823f6c13701
Title: CAFE RACER BIKE CG MODEL
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default  function Model(props) {
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-0.262, -1.458, 0.364]} rotation={[0.029, 0, 0]} scale={0.428}>
          <mesh geometry={nodes.Cube420_ENGINE_0.geometry} material={materials.ENGINE} />
          <mesh geometry={nodes.Cube420_ENGINE_0_1.geometry} material={materials.ENGINE} />
          <mesh geometry={nodes.Cube420_ENGINE_0_2.geometry} material={materials.ENGINE} />
          <mesh geometry={nodes.Cube420_ENGINE_0_3.geometry} material={materials.ENGINE} />
          <mesh geometry={nodes.Cube420_ENGINE_0_4.geometry} material={materials.ENGINE} />
        </group>
        <group position={[2.377, 34.316, -5.829]} rotation={[-1.565, 0, Math.PI / 2]} scale={102.07}>
          <mesh geometry={nodes.polySurface5_TYRE_0.geometry} material={materials.TYRE} />
          <mesh geometry={nodes.polySurface5_TYRE_0_1.geometry} material={materials.TYRE} />
          <mesh geometry={nodes.polySurface5_TYRE_0_2.geometry} material={materials.TYRE} />
        </group>
        <group position={[-0.262, -1.458, 0.364]} rotation={[0.029, 0, 0]} scale={0.428}>
          <mesh geometry={nodes.Plane002_LIGHTS_0.geometry} material={materials.LIGHTS} />
          <mesh geometry={nodes.Plane002_LIGHTS_0_1.geometry} material={materials.LIGHTS} />
          <mesh geometry={nodes.Plane002_EMESSION_0.geometry} material={materials.EMESSION} />
          <mesh geometry={nodes.Plane002_standardSurface1_0.geometry} material={materials.standardSurface1} />
        </group>
        <group position={[-0.262, -1.458, 0.364]} rotation={[0.029, 0, 0]} scale={0.428}>
          <mesh geometry={nodes.Plane003_GLASS_0.geometry} material={materials.GLASS} />
          <mesh geometry={nodes.Plane003_GLASS001_0.geometry} material={materials['GLASS.001']} />
          <mesh geometry={nodes.Plane003_SIDE_GLASS_0.geometry} material={materials.SIDE_GLASS} />
        </group>
        <mesh geometry={nodes.Cylinder009_TANK_0.geometry} material={materials.TANK} position={[-0.262, -1.458, 0.364]} rotation={[0.029, 0, 0]} scale={0.428} />
        <mesh geometry={nodes.polySurface1_TYRE_0.geometry} material={materials.TYRE} position={[0, -14.074, 0]} rotation={[0.029, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.gltf')
